import type { Metadata } from "next";
import Script from "next/script";
import LenisContainer from "@/components/LenisContainer";
import 'prismjs/themes/prism-tomorrow.css';

export const metadata: Metadata = {
  title: "Kode eksempler og Kode oppgave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/themes/prism-tomorrow.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <LenisContainer>
          {children}
        </LenisContainer>

        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/prism.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/components/prism-html.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
};
