import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisContainer from "@/components/LenisContainer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hjem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-[--font-geist-mono] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisContainer>
          {children}
        </LenisContainer>
      </body>
    </html>
  );
}
